services:
  frontend:
    image: ghcr.io/dtx-dota/website/frontend:latest
    ports:
      - "3000:3000"   # Internal Nginx in frontend container
    restart: always
    
  backend:
    image: ghcr.io/dtx-dota/website/backend:latest
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
